### ISSUE TITLE
Uninitialized constant EasyPost Error

### ISSUE THREAD

**Issue by nhippenmeyer** [solidusio-contrib/solidus_easypost#14]
When installing this gem and following the setup instructions, I get an `/Users/nhippenmeyer/src/web/config/initializers/easy_post.rb:1:in `<top (required)>': uninitialized constant EasyPost (NameError)` error when starting the rails server.

Also running `rake railties:install:migrations` doesn't generate any migrations.

I'm on the following versions:

ruby 2.3.1p112
Bundler version 1.12.5
Rails 4.2.7.1
Solidus 1.3.1

**Comment by qr8r** [comment]
Thanks for bringing this up. It looks like when the name changed in the gemspec, bundler wasn't requiring the gem properly into project. This is fixed in #16 and Ive released v1.0.4 with this fix
