### ISSUE TITLE
Reprice expired labels

### ISSUE THREAD

**Issue by ericgross** [solidusio-contrib/solidus_easypost#20]
When the user checks out, we request the rates from Easypost and purchase a particular rate. It can be an extended amount of time before an administrator clicks on the Ship button in the admin interface. Sometimes the purchased rate has expired which prevents the order from being shipped.

I propose that when a shipping rate has been purchased and when an exception is thrown when purchasing a shipment, we should re-rate the shipment in Easypost and then try again to transition the `shipment` to `shipped` which will call `buy_easypost_rate` again.

**Comment by seandawes** [comment]
@ericgross Why is it an extended period of time from user request to admin selecting ship in admin? Manually processing orders so request to purchase is time outside business hours (ie weekends) or instances of validation needs to occur before capturing payment on user orders?

Or you modifying the shipment in some manner prior to needing to recalculate? 

Just looking for more specific details on the use case

**Comment by seandawes** [comment]
@ericgross pinging you again
