### ISSUE TITLE
rake railties:install:migrations

### ISSUE THREAD

**Issue by gildardoperez** [solidusio-contrib/solidus_easypost#30]
Also running rake railties:install:migrations doesn't generate any migrations.

I'm on the following versions:

ruby 2.5.3
Rails 5.2.2
Solidus 2.7.1

**Comment by znedw** [comment]
Same here, getting the following when I try start with the initialiser:

`NameError: uninitialized constant EasyPost`

**Comment by gildardoperez** [comment]
@peterberkenbosch I'm still not seeing the migrations, I tested both Solidus 2.7.1 and solidus 2.8.0 on solidus_easypost 1.0.5 any ideas why? Thanks

**Comment by peterberkenbosch** [comment]
@gildardoperez yes, there has not been a release yet. So 1.0.5 will still have the problem. I think the PR is good to merge now, it will have a new version then too (2.0.0). You could also use my fork for the time being. 

Gemfile:
```
gem 'solidus_easypost', github: 'peterberkenbosch/solidus_easypost', branch:'fix-engine-loading'
```

**Comment by gildardoperez** [comment]
👏 Thank you all!
