### ISSUE TITLE
Config is now frozen.

### ISSUE THREAD

**Issue by Mikewa33** [solidusio-contrib/solidus_easypost#49]
https://github.com/solidusio-contrib/solidus_easypost/commit/c7d506e9001c7cf9699e891e34ee4f6eebbbe34a#diff-4e63e951a95590f5ed3ee43898371185

Was this change intentional? It stops the config in the readme from being setup
``` # config/initializers/easy_post.rb
  Solidus::EasyPost::CONFIGS[:purchase_labels?] = false

**Comment by aldesantis** [comment]
@Mikewa33 this was not intentional, it's now fixed in master. Thanks for catching it!
